name: MSBuild

on: [push, pull_request]

jobs:
  msbuild:
    runs-on: windows-latest

    strategy:
      matrix:
        configuration: [Release]
        platform: [x64]

    steps:
    - uses: actions/checkout@v4

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v2

    - name: Build
      working-directory: ${{ env.GITHUB_WORKSPACE }}
      run: msbuild TextmodeTF2.sln /p:Platform=${{ matrix.platform }} /p:Configuration=${{ matrix.configuration }}
    
    - uses: actions/upload-artifact@v4
      with:
        name: TextmodeTF2${{ matrix.platform }}${{ matrix.configuration }}
        path: output/${{ matrix.platform }}/${{ matrix.configuration }}/*.dll
